version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: postgres:15.4-alpine3.18
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_DB: dticket
    volumes:
      - /var/lib/postgres/data:/var/lib/postgresql/data
